version: "3.8"
services: 
    app:
        build: 
            context: ./Python/
        ports:
            - 5000:5000
        volumes:
            - ./Python:/ecommerce
        depends_on: 
            - db
        env_file:
            - .env
            
    db:
        build: 
            context: ./Database/
            args:
                - MYSQL_USER=${MYSQL_USER}
                - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                - MYSQL_DATABASE=${MYSQL_DATABASE}
                - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
        env_file:
            - .env
    
volumes: 
    mysql:
    mysql_config: